version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:TIzUGyoZEiyQbRvbffjX5OzWFXnyS0uW/vmOcCBS/bQ=
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=db1
      - DB_USERNAME=postgres
      - DB_PASSWORD=123
      - VITE_APP_NAME=Laravel
    volumes:
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs
    networks:
      - laravel_network

  db:
    image: postgres:15-alpine
    container_name: laravel_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel_network

volumes:
  postgres_data:

networks:
  laravel_network:
    driver: bridge