version: '3.8'
services:
  postgres: # Or 'db' if you prefer, just ensure DB_HOST matches
    image: postgres:16.9 # Pin to a specific version for stability
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: db1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ayoub2003
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data # Use a named volume for better management
    ports:
      - "5432:5432"
  laravel_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80" # Example port mapping for your Laravel app
    depends_on:
      - postgres # Ensure postgres_db starts before laravel_app
    environment:
      # Pass database credentials to Laravel
      DB_CONNECTION: pgsql
      DB_HOST: postgres # Matches the service name
      DB_PORT: 5432
      DB_DATABASE: db1
      DB_USERNAME: postgres
      DB_PASSWORD: Ayoub2003
      APP_URL: http://localhost:8000 # Good practice for Laravel apps
    volumes:
      - ./backend:/var/www/html

volumes:
  pgdata: # Define the named volume